### ISSUE TITLE
Telldus Live! API responded with error: "The remote server returned an error: (401) Unauthorized."

### ISSUE THREAD

**Issue by anden04** [AWahlqvist/powershell-tellstick-module#3]
I don't know if I'm doing something wrong, but when I try to use the Connect-TelldusLive cmdlet and enter my credentials, I get this error:

Exception: Failed to connect to Telldus Live! The error was: Telldus Live! API responded with error: "The remote server returned
an error: (401) Unauthorized."

Is it just me or is something wrong with this module?

**Comment by AWahlqvist** [comment]
@jonas04anderberg : Are you using the "Credential" parameter to enter your credentials? It's only meant to be used if you have a known access token. The module never needs your actual credentials since it uses the OAuth flow.

To authenticate the module, you can do the following:
`Connect-TelldusLive -SaveCredential`

Follow the URL posted back by the module to go to Telldus Live and authenticate the module, after that the access token will be saved (encrypted) locally on your computer so it can be reused with authenticating through the website again, simply run:
`Connect-TelldusLive -UseSavedCredential`

...and you should be good to go!

Hope this helps, otherwise feel free to get back to me :-)

**Comment by anden04** [comment]
> @jonas04anderberg : Are you using the "Credential" parameter to enter your credentials? It's only meant to be used if you have a known access token. The module never needs your actual credentials since it uses the OAuth flow.
> 
> To authenticate the module, you can do the following: `Connect-TelldusLive -SaveCredential`
> 
> Follow the URL posted back by the module to go to Telldus Live and authenticate the module, after that the access token will be saved (encrypted) locally on your computer so it can be reused with authenticating through the website again, simply run: `Connect-TelldusLive -UseSavedCredential`
> 
> ...and you should be good to go!
> 
> Hope this helps, otherwise feel free to get back to me :-)

Thank you very much! That worked. Closing the thread.
